### ISSUE TITLE
Error executing 'postInstallation': Failed to connect to redis-primary:6379 after 36 tries redis-slave_1 exited with code 1

### ISSUE THREAD

**Issue by syst0m** [bitnami/bitnami-docker-redis#103]
Trying to access the bitnami redis containers from a php container.
Can read/write to redis-master, redis-slave is failing when not using authentication parameters.
Looks like it's trying to connect to the master on redis-primary:6379.

Shouldn't the slave communicate with the master on the cluster bus port, i.e. 16379, and not the client port: 6379?

checking keys on redis-slave:

```
# redis-cli -h 0.0.0.0 -p 2124
0.0.0.0:2124> keys *
Error: Connection reset by peer

```
docker-compose.yaml excerpt:

 ```
 fix-redis-permissions:
    image: 'bitnami/redis:latest'
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - /redis-master:/bitnami

  redis-master:
    build:
      context: ./redis-master
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
  #  volumes:
  #    - '/redis-master:/bitnami'
    depends_on:
      - fix-redis-permissions

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
```
docker logs -f:

```
redis-slave_1            | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis-slave_1            | nami    INFO  Initializing redis
redis-slave_1            | redis   INFO  ==> Validating inputs...
redis-slave_1            | redis   WARN  Allowing the "password" input to be empty
redis-slave_1            | redis   WARN  Allowing the "masterPassword" input to be empty
redis-slave_1            | redis   INFO  ==> Configuring replication settings...
redis-slave_1            | redis   INFO  ==> Checking if master is ready to accept connection...
redis-slave_1            | Error executing 'postInstallation': Failed to connect to redis-primary:6379 after 36 tries
redis-slave_1 exited with code 1

```

- Output of `docker version`:
> Docker version 1.13.1, build 092cba3

- Output of `docker info`:

> Containers: 140
>  Running: 5
>  Paused: 0
>  Stopped: 135
> Images: 438
> Server Version: 1.13.1
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 679
>  Dirperm1 Supported: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
> runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
> init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.13.0-26-generic
> Operating System: Ubuntu 16.04.3 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 12
> Total Memory: 125.8 GiB
> Name: comprigo-staging3
> ID: SKVU:MEHB:QODI:MNU7:4SCQ:IR4Z:H576:4XCM:CTXP:Q4IE:EXI7:IHDP
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Username: comprigottomasic
> Registry: https://index.docker.io/v1/
> WARNING: No swap limit support
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> 

- Output of `docker-compose version` (if applicable):

> docker-compose version 1.8.0, build unknown

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Running on bare-metal. 

>  #lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial

> #uname -a
> Linux comprigo-staging3 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
