### ISSUE TITLE
Fatal error, can't open config file '/opt/bitnami/redis/conf/redis.conf'

### ISSUE THREAD

**Issue by thesobercoder** [bitnami/bitnami-docker-redis#104]
**Description**

Trying to deploy a Redis cluster with the following `docker-compose.yml` fails
```
version: '3'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=laSQL2019
      - REDIS_EXTRA_FLAGS='--maxmemory 100mb'
    volumes:
      - '/redis-volume:/bitnami'
    deploy:
      placement:
        constraints: [node.role == manager]

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
      - '/redis-volume:/bitnami'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=laSQL2019
      - REDIS_PASSWORD=laSQL2019
      - REDIS_EXTRA_FLAGS='--maxmemory 100mb --appendonly yes'
      
volumes:
  redis-volume:
```

with the following log

```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

PROT_EXEC|PROT_WRITE failed.
INFO  ==> Starting redis...
sed: can't read /opt/bitnami/redis/conf/redis.conf: No such file or directory
14:C 25 Apr 19:38:53.903 # Fatal error, can't open config file '/opt/bitnami/redis/conf/redis.conf'
```

**Steps to reproduce the issue:**

1. Create the `docker-compose.yml`
2. Run command `docker stack deploy -c docker-compose.yml redis`
3. Check container logs

**Describe the results you received:**

The containers are not starting.

**Describe the results you expected:**

The containers should've started.

**Version**

- Output of `docker version`:

```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    9584b2309e
 Built: Wed Mar  7 13:17:02 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   v17.12.1-ce
  Built:        Wed Mar  7 13:16:22 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:

```
Containers: 19
 Running: 1
 Paused: 0
 Stopped: 18
Images: 2
Server Version: 17.12.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: rppuzu9c6h931fyz7f1jb26js
 Is Manager: true
 ClusterID: hciv58fl1ddofyfyvajno1rf9
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.56.101
 Manager Addresses:
  192.168.56.101:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9584b2309e5be604504d4a8ff7ef5def5b42e9a0 (expected: 9b55aab90508bd389d7654c4baf173a981477d55)
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f (expected: 9f9c96235cc97674e935002fc3d78361b696a69e)
init version: 949e6facb77383876aeff8a6944dde66b3089574
Kernel Version: 4.9.65-1-virthardened
Operating System: Alpine Linux v3.7
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956GiB
Name: node-1
ID: VOCD:NX26:P6QS:J4HW:2WHT:O4TY:2L5R:ZXRW:63O7:K35I:B5W3:OLQ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.0, build 5920eb0
docker-py version: 3.2.1
CPython version: 2.7.14
OpenSSL version: LibreSSL 2.6.3
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* Laptop OS: Windows 10
* VirtualBox: 5.2.8
* No. of VMs: 3
* VM OS: Alpine Linux 3.7.0

**Comment by juan131** [comment]
Hi @thesobercoder 

Are you using the same volume for both Master and Slave containers? I also noticed you're quoting the **REDIS_EXTRA_FLAGS** values, please do not do it. Try with this docker-compose.yaml:

```
version: '3'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=laSQL2019
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb
    volumes:
      - 'redis-master-volume:/bitnami'
    deploy:
      placement:
        constraints: [node.role == manager]

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-slave-volume:/bitnami'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=laSQL2019
      - REDIS_PASSWORD=laSQL2019
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb --appendonly yes

volumes:
  redis-master-volume:
    driver: local
  redis-slave-volume:
    driver: local
```
