### ISSUE TITLE
Sentinel setup fails in docker swarm mode

### ISSUE THREAD

**Issue by thesobercoder** [bitnami/bitnami-docker-redis#105]
**Description**

Trying to setup a Redis Sentinel setup in docker swarm mode fails. The following `docker-compose.yml` describes what I'm trying to achieve. Even though the `bitnami-docker-redis` documentation states that in swarm mode there should not be more than 1 master but a practical production Redis setup according to Redis documentation requires more than 1 master since there is always a possibility of the single master node to fail.

```
version: '3'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=laSQL2019
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb
    volumes:
      - 'redis-master-volume:/bitnami'
    deploy:
      mode: replicated
      replicas: 2

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-slave-volume:/bitnami'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=laSQL2019
      - REDIS_PASSWORD=laSQL2019
      - REDIS_EXTRA_FLAGS=--maxmemory 100mb
    deploy:
      mode: replicated
      replicas: 2
      
  redis-sentinel:
    image: 'bitnami/redis:latest'
    ports:
      - '26379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-sentinel-volume:/bitnami'
    environment:
      - REDIS_PASSWORD=laSQL2019    
      - REDIS_EXTRA_FLAGS=--sentinel monitor redis-sentinel redis-master 
    deploy:
      mode: global
            
volumes:
  redis-master-volume:
    driver: local
  redis-slave-volume:
    driver: local
  redis-sentinel-volume:
    driver: local
```

**Steps to reproduce the issue:**

1. Create a `docker-compose.yml` file from above code
2. Run `docker stack deploy -c docker-compose.yml redis`
3. Check container logs

**Describe the results you received:**

The Sentinel container failed to start with the following log.

```
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
redis   INFO
redis   INFO  ########################################################################
redis   INFO   Installation parameters for redis:
redis   INFO     Password: **********
redis   INFO   (Passwords are not shown for security reasons)
redis   INFO  ########################################################################
redis   INFO
nami    INFO  redis successfully initialized
INFO  ==> Starting redis...

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 1319
>>> 'sentinel "monitor" "redis-sentinel" "redis-master"'
Unrecognized sentinel configuration statement.
```

**Describe the results you expected:**

The sentinel container should've started acting as a single point of contact for all Redis queries.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:21:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Output of `docker info`:

```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:21:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
[rancher@rancher ~]$ ^C
[rancher@rancher ~]$ clear
[rancher@rancher ~]$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.09.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: snyslw41hw5hhkuwwzt1b4dfa
 Is Manager: true
 ClusterID: ilidn8dn3kwg3pqzf6t2147v7
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.1.20
 Manager Addresses:
  192.168.1.20:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.80-rancher
Operating System: RancherOS v1.3.0
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.9MiB
Name: rancher
ID: 7BLM:BY7A:AGAX:QFCG:73WI:3FXN:X5A6:OTWL:S7S2:VUVL:WIPW:GKIO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* Docker Swarm Config: 1 Master node, 3 Workers
* OS: RancherOS 1.3.0
