### ISSUE TITLE
Helm chart 3.0.5 fails to start with "Can't open the append-only file: Permission denied"

### ISSUE THREAD

**Issue by FuzzOli87** [bitnami/bitnami-docker-redis#106]
**Description**
When attempting to deploy Helm chart(version 3.0.5) I get a ```Can't open the append-only file: Permission denied``` error on the master and it does not initialize.

**Steps to reproduce the issue:**

1. helm install --set usePassword=false --set metrics.enabled=true --set master.securityContext.enabled=false  --name scout-processor-db-redis stable/redis

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/12246915/39486578-452e64ea-4d42-11e8-946c-a8fce75e5a02.png)

**Describe the results you expected:**

For the container to start

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm running this on Kubernetes 1.9.3 installed via KOPS on AWS.

**Comment by tompizmor** [comment]
I don't think you should disable the securityContext settings.  
As redis is a non-root container it requires that the volumes used in the chart are owned by the same user that is running redis. This means that the volumes should be owned by the user `1001` as it is the user running redis by default (https://github.com/bitnami/bitnami-docker-redis/blob/master/4.0/Dockerfile#L24)

**Comment by FuzzOli87** [comment]
@tompizmor I agree and I wouldn't want to disable the security settings. However, they seem to be causing an issue with Istio and because this was a QA environment I wanted to get it up and going and hopefully have this looked at by the Istio team in the meanwhile.

**Comment by tompizmor** [comment]
Which is the issue if you have the security settings enabled?

I think you could try two things:
1. Keep running the container as non-root, disable the security settings but use an initContainer to change the permission of the volume. You can see an example in the [stable ghost chart](https://github.com/kubernetes/charts/blob/master/stable/ghost/templates/deployment.yaml#L24-L31).
2. Run the container as root using this security settings:

    ```
      securityContext:
        runAsUser: 0
    ```

**Comment by cog-qlik** [comment]
I solved the wrong permissions using
```yaml
securityContext:
      fsGroup: 2000
```
as suggested in the example [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).

**Comment by tompizmor** [comment]
I am glad that you were able to get it working!

**Comment by cog-qlik** [comment]
@tompizmor I'd say that I haven't seen it in a few days at least ^^

**Comment by cog-qlik** [comment]
Unfortunately the solution above didn't help either. I don't know why it seemed to work out for a few days.
Still looking for a solution since this problem is quite annoying -.-

For what I've seen, the `helm install` works fine if the cluster has never seen any redis' chart deployment before. If you `helm install`, `helm delete` and then `helm install` again the problem arises.

**Comment by tompizmor** [comment]
Could you please let me know how I could reproduce the issue? 
I have never tried istio before so not sure if I should make some configurations before install the redis chart. 

Also, did you install the redis helm chart with any specific setting?

**Comment by cog-qlik** [comment]
Actually I'm not using istio. In my case the Redis chart is a dependency of another chart and it's configured as follows:
```yaml
redis:
  image:
    pullPolicy: IfNotPresent
  usePassword: false
  cluster:
    enabled: false
  master:
    statefulset:
      updateStrategy: RollingUpdate
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
``` 
I guess it's not such a fancy configuration. Any help is much appreciated.

**Comment by cog-qlik** [comment]
1. minikube `v0.27.0` (has RBAC enabled by default)
2. the `requirements.lock` looks as follows:
```
dependencies:
- name: redis
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.5.0
digest: sha256:ccd171904d7457439ed4c039171f1fd08626e7c7520d25ffcd31f1448c1baf03
generated: 2018-06-21T11:31:57.03001444+02:00
```
3. It seems like the behaviour can be seen doing a `helm install`, `helm delete --purge` and `helm install again`. On the other hand, if you `helm install` and then `helm upgrade` only (which is what is done in production ideally) it _seems_ to work.

**Comment by tompizmor** [comment]
I am still unable to reproduce the issue 😞

I am using the same minikube version (v0.27.0), the same redis chart version (3.5.0), the same [configuration](https://github.com/bitnami/bitnami-docker-redis/issues/106#issuecomment-400945017) as a subchart and I am also doing `helm install`, `helm delete --purge` and `helm install` again and it always work.

- Are you able to reproduce the issue always?
- What is your kubernetes version?
- What is your host OS?

**Comment by tompizmor** [comment]
@salamander-mh can you translate your reply to English? 
Also, at this moment the Redis Bitnami image is not based on alpine. Are you sure you are using the docker image from Bitnami?

**Comment by salamander-mh** [comment]
@tompizmor 
sorry, My image is based on officical redis.

**Comment by carrodher** [comment]
No problem, if you have any question related to the bitnami image don't hesitate to ask here!

**Comment by slaterx** [comment]
I've got this issue on 4.0.12-ol-7-r23.

My workaround was to manually create appendonly.aof and dump.rdb on the data folder. With that, the container starts successfully.

**Comment by tompizmor** [comment]
Thanks for sharing your workaround!
Did you install the helm chart with any specific options or did you use the default values.yaml?

**Comment by strowi** [comment]
Same issue happens with docker-compose:
```
version: '2.1'

services:
  master:
    image: 'bitnami/redis:5.0.3-debian-9-r24'
    restart: always
    sysctls:
      - net.core.somaxconn=511
    ports:
      - '6000:6379'
    command: /run.sh --maxmemory 50gb --databases 64
    volumes:
      - ../00-redis_data_master:/bitnami/redis/data
```

```
master_1      | INFO  ==> ** Starting Redis setup **
master_1      | INFO  ==> Initializing Redis...
master_1      | INFO  ==> ** Redis setup finished! **
master_1      | 
master_1      | INFO  ==> ** Starting Redis **
master_1      | 1:C 21 Jan 2019 14:30:05.236 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
master_1      | 1:C 21 Jan 2019 14:30:05.236 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
master_1      | 1:C 21 Jan 2019 14:30:05.236 # Configuration loaded
master_1      | 1:M 21 Jan 2019 14:30:05.236 # Can't open the append-only file: Permission denied

```
