### ISSUE TITLE
Clients cant write to master node with 'client' password

### ISSUE THREAD

**Issue by camAtGitHub** [bitnami/bitnami-docker-redis#109]
**Description**

Running redis using documented instructions causes the 'master' to use the same password as the 'master_password' (for joining the cluster) as the same password as allowing clients to perform writes.

Therefore slaves and master have different client access passwords and no applications could write to the redis store.

**Steps to reproduce the issue:**

Use a docker-compose like:
```
---
# https://hub.docker.com/r/bitnami/redis/
version: '2' 
services:
  master:
    image: bitnami/redis:4.0.11
    environment:
      REDIS_REPLICATION_MODE: 'master'
      REDIS_PASSWORD: 'someMasterPassword' # Join cluster
    volumes:
      - /srv/redis-master:/bitnami:rw
  slave:
    image: bitnami/redis:4.0.11
    environment:
      REDIS_REPLICATION_MODE: 'slave'
      REDIS_MASTER_HOST: 'master'
      REDIS_MASTER_PORT: '6379'
      REDIS_MASTER_PASSWORD: 'someMasterPassword' # Join cluster
      REDIS_PASSWORD: 'someClientPassword' # Client password
    volumes:
      - /srv/redis-slave:/bitnami:rw
```

**Describe the results you received:**

Clients can't write to the master

**Describe the results you expected:**

Clients are to access the master writes with someClientPassword
