### ISSUE TITLE
docker-compose Data Persistence: CAn't open the append-only file: Permission Denied

### ISSUE THREAD

**Issue by plambhsa** [bitnami/bitnami-docker-redis#121]
**Description**

I am trying to start a redis instance using docker-compose, with a volume mapped to the `/bitnami/redis/data` folder as described in the README. However, when I have the volume mapped and try to start the container using docker-compose up, I get an error after the configuration is loaded of: Can't open the append-only file: Permission denied.

**Steps to reproduce the issue:**

1. Add the below info to a docker-compose.yml file
2. Run `docker-compose up` or `docker-compose up -d`

docker-compose.yml:

```yml
version: '3'

services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=snxtasntuisntoesnidasontxahosetidasonetdihasoetdiasontdqq
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/bitnami/redis/data
```

**Describe the results you received:**

The container tries to start, but an error stops it from finishing the start up.

**Describe the results you expected:**

The redis container should've started with the volume mapping so that data can persist.

**Version**

- Output of `docker version`:

```
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:57 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:30 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.19.0, build 9e633ef
```

This is on a Linux VM in a Google Cloud Environment
