### ISSUE TITLE
Helm release fails for version 4.0.0 using helmfile.

### ISSUE THREAD

**Issue by charlesbthomas** [bitnami/bitnami-docker-redis#133]
When trying to use the helm template with the following values on version 4.0.0 the master and slave pods are all terminating with the following log.

```sed: -e expression #1, char 45: unterminated `s' command```

The version of the helm chart being used is 4.0.0 and I am providing the following values.

```
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "my-namespace"
    selector: { prometheus: my-prometheus }

cluster:
  enabled: true
  slaveCount: 2

existingSecret: redis-password
```
