### ISSUE TITLE
DENIED: Redis is running in protected mode

### ISSUE THREAD

**Issue by pdkproitf** [bitnami/bitnami-docker-redis#136]
**Please save my struggle**

**Steps to reproduce the issue:**

My docker-compose.yml
```
 redis:
    image: bitnami/redis:latest
    container_name: first_redis
    command: ["redis-server", "--appendonly", "yes"]
    user: root
    ports:
      - '6379:6379'
    volumes:
      - db-redis:/bitnami/redis/data
    environment:
      REDIS_APPENDFSYNC: "always"
      ALLOW_EMPTY_PASSWORD: "yes"
      DISABLE_COMMANDS: FLUSHDB,FLUSHALL
```

**Describe the results you received:**
<img width="1416" alt="screen shot 2019-01-08 at 4 26 50 pm" src="https://user-images.githubusercontent.com/12691828/50821770-a35cc700-1362-11e9-9c23-45067ba883b6.png">

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 18.09.0
```

- Output of `docker info`:

```
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
