### ISSUE TITLE
[feature request] add simple healthcheck

### ISSUE THREAD

**Issue by mebibou** [bitnami/bitnami-docker-redis#139]
Would it be possible to add a simple `healthcheck` script similar to [this one](https://github.com/docker-library/healthcheck/blob/master/redis/docker-healthcheck) ?

**Comment by javsalgar** [comment]
We have healthchecks set in the Helm chart template. Could you elaborate more the reasons for wanting this in the container? This way we can better evaluate in the team.

**Comment by mebibou** [comment]
I was using the image along with the `bitnami/discourse` image, and the redis container stopped working properly and I only figured it out a while later. After a restart everything seemed fine, but I have alerts triggered based on healthcheck on containers and wanted to have it on the redis one

**Comment by javsalgar** [comment]
Which container platform are you using?

**Comment by mebibou** [comment]
I am not sure what you mean by platform but I am using docker-compose 1.18.0 and the config:
```
version: '2.2'

services:
  postgresql:
    image: bitnami/postgresql:9.6
    restart: unless-stopped
    volumes:
      - postgresql_data:/bitnami

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis:/opt/cr
      - redis_data:/bitnami

  discourse:
    image: bitnami/discourse:latest
    restart: unless-stopped
    labels:
      kompose.service.type: nodeport
    ports:
      - '3003:3000'
    depends_on:
      - postgresql
      - redis
    volumes:
      - discourse_data:/bitnami
    healthcheck:
      test: "curl -f http://localhost:3000 || false"

  sidekiq:
    image: bitnami/discourse:latest
    restart: unless-stopped
    depends_on:
      - discourse
    volumes:
      - sidekiq_data:/bitnami
    command: 'nami start --foreground discourse-sidekiq'

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
```
