### ISSUE TITLE
Keep getting NOAUTH after the redis run for a little bit of time

### ISSUE THREAD

**Issue by dummys** [bitnami/bitnami-docker-redis#140]
Hi,

I'm using docker-compose to generate my container, and everything is working correctly for some time and then I start getting NOAUTH authentication log and I can't connect anymore to redis.
What can be the issue ?

**Comment by dummys** [comment]
docker compose: 

```
version: '3.2'

networks:
  mntools_network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - /redis:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - mynet_network
```

version is the latest from bitnami
