### ISSUE TITLE
Container start works only after destroying the existing one

### ISSUE THREAD

**Issue by mhe-de** [bitnami/bitnami-docker-redis#143]
**Container start works only after destroying the existing one**

1. git clone https://github.com/bitnami/bitnami-docker-redis
2. docker-compose up
3. docker-compose stop
4. docker-compose up

**Describe the results you received:**
```
redis_1  |
redis_1  | Welcome to the Bitnami redis container
redis_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis_1  | Send us your feedback at containers@bitnami.com
redis_1  |
redis_1  | INFO  ==> ** Starting Redis setup **
redis_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis_1  | INFO  ==> Initializing Redis...
new_redis_1 exited with code 1
```
**Describe the results you expected:**
Container should start

**Additional information you deem important (e.g. issue happens only occasionally):**
** Used compose file **
```
version: '2'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'

volumes:
  redis_data:
    driver: local
```

**Version**

- Output of `docker version`:

```
Docker version 18.09.2, build 6247962
```

- Output of `docker info`:

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 224
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: Q5SJ:VWGB:S4JN:RU7T:RVWX:S7G4:XXB6:EYPC:43HX:D7SM:K2WC:FH7C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 54
 System Time: 2019-03-14T07:09:32.0871668Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```
