### ISSUE TITLE
Version 5.0.8 fails to start and raise `Fatal error, can't open config file '/opt/bitnami/redis/etc/redis.conf'`

### ISSUE THREAD

**Issue by francoislefebvre** [bitnami/bitnami-docker-redis#160]
**Description**

Using `bitnami/redis` image with  digest `ae9c83c40ac0` (5.0.8) cause the container to fail to start with message `Fatal error, can't open config file '/opt/bitnami/redis/etc/redis.conf'` It use to be fine with  digest `30303b8533` (5.0.7-debian-10-r20).

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**
 
Container fails to start with message `Fatal error, can't open config file '/opt/bitnami/redis/etc/redis.conf'`

**Describe the results you expected:**

Container starts as usual.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
\Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:35:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 19
Server Version: 18.09.4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: nvidia runc
Default Runtime: nvidia
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30-dirty
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-91-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.6GiB
Name: *********** (hidden)
ID: YD4L:DDLE:MUUI:FUHW:BKU3:SB6L:3P3F:6LKT:6G3F:JBSV:U5WP:K6AW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 ************** (hidden)
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- Docker-compose config

```
redis:
    container_name: "redis"
    pid: "redis"
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=**********
    ports:
      - "6379:6379"
    command: ./run.sh --appendonly yes
    volumes:
      - redis_volume:/bitnami/redis/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
```

**Comment by Mauraza** [comment]
Hi @francoislefebvre,

the script ` /run.sh` is for the creation of the container. If you remove that line will be working fine. And you by default the `appenonly` get the value yes. 

```
version: '2'

services:
  redis:
    container_name: "redis"
    image: 'bitnami/redis:5.0'
    environment:
      - REDIS_PASSWORD=bitnami
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/bitnami/redis/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
volumes:
  redis_volume:
    driver: local

```

**Comment by Power2All** [comment]
Confirmed, same issue. Switched back 5.0.7 and solved the problem.

**Comment by Mauraza** [comment]
Hi @Power2All, 

you are right, we will investigate more about what it's happened. When we fixed I update this thread with more news.

Thanks for reporting!

**Comment by beltran-rubo** [comment]
Hi @Power2All @francoislefebvre 

This could be related to the latest change in the CMD command. We moved the "run.sh" script into '/opt/bitnami/scripts/redis/run.sh', see the Dockerfile. See the "command" option in the docker-file.yml below.

```
version: '2'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    command: /opt/bitnami/scripts/redis/run.sh --appendonly yes
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
```

**Comment by beltran-rubo** [comment]
Please confirm that approach works for you so we will close this issue, thanks.

**Comment by francoislefebvre** [comment]
Yes, this approach works. Thanks.

**Comment by Power2All** [comment]
Confirmed working, thanks for the time @beltran-rubo

**Comment by augi** [comment]
I've also ran into this issue. The change was introduced in [this commit](https://github.com/bitnami/bitnami-docker-redis/commit/23d246dcfd14cacc555c596fd221c982c34a21d7). It would be great to mention this change in [README](https://github.com/bitnami/bitnami-docker-redis#notable-changes) ❤️

**Comment by loremaps** [comment]
I think there is still a regression issue with `5.0.8`. The following example deployment is working fine with `5.0.7` but not with `5.0.8`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: bitnami/redis:5.0.8
        ports:
        - containerPort: 6379
```
In the logs:

```
[38;5;6m [38;5;5m09:25:59.20 [0m[38;5;2mINFO [0m ==> ** Starting Redis **
1:C 10 Apr 2020 09:25:59.211 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 10 Apr 2020 09:25:59.211 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 10 Apr 2020 09:25:59.211 # Configuration loaded
1:M 10 Apr 2020 09:25:59.212 # Configured to not listen anywhere, exiting.
```

Am I missing something?
