### ISSUE TITLE
Version 5.0.8 terminating with 'Configured to not listen anywhere, exiting'

### ISSUE THREAD

**Issue by loremaps** [bitnami/bitnami-docker-redis#163]
**Description**

With `5.0.8` release, the pod terminates with the message `Configured to not listen anywhere, exiting.` 

**Steps to reproduce the issue:**

1. Create a namespace e.g. `kubectl create namespace redis-test`
2. apply the following resources
```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          value: test
        image: bitnami/redis:5.0.8
        name: redis
        ports:
        - containerPort: 6379
        resources: {}

```

**Describe the results you received:**

Pod is terminating with the following log:
```
1:C 10 Apr 2020 10:50:34.506 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 10 Apr 2020 10:50:34.506 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 10 Apr 2020 10:50:34.506 # Configuration loaded
1:M 10 Apr 2020 10:50:34.506 # Configured to not listen anywhere, exiting.
```

**Describe the results you expected:**

I would expect the pod to run, same as `5.0.7`

**Additional information you deem important (e.g. issue happens only occasionally):**

If you omit the service the pod is not terminating. But it does not seem to produce any logs either.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 38
  Running: 34
  Paused: 0
  Stopped: 4
 Images: 234
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.777GiB
 Name: docker-desktop
 ID: J4RL:CZJQ:33A3:G3XH:D6GE:RLM5:4SSR:Y5SA:I2WK:5UNX:34QH:6TBW
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 262
  Goroutines: 275
  System Time: 2020-04-10T10:56:13.7669253Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Observed on Kubernetes v1.15.5 (docker-for-mac) and GKE

**Comment by rba4062** [comment]
Same issue on the following Kubernetes version 
```
 kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

```1:C 10 Apr 2020 11:03:13.317 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 10 Apr 2020 11:03:13.317 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 10 Apr 2020 11:03:13.317 # Configuration loaded
1:M 10 Apr 2020 11:03:13.318 # Configured to not listen anywhere, exiting.
```

**Comment by Mauraza** [comment]
Hi @loremaps,

you need to add `REDIS_PORT` to the deployment. it would look like this:

```
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: bitnami/redis:5.0.8-debian-10-r36
        env:
        - name: REDIS_PASSWORD
          value: test
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 6379
```
