### ISSUE TITLE
zombie processes

### ISSUE THREAD

**Issue by fmax** [bitnami/bitnami-docker-redis#165]
**Description**
when running helm app in kubernetes with template version 9.0.2 from time to time 'redis-cli' zombie processes get produced

maybe the are caused by the health checks for readiness / liveness checks.

**Steps to reproduce the issue:**

start kubernetes app with following answers (yaml)
```
  cluster: 
    enabled: true
    slaveCount: "2"
  usePassword: true
  password: "my-secret"
  master:
    persistence: 
      enabled: true
      size: "1Gi"
      storageClass: "my-ceph"
    service: 
      type: "ClusterIP"
      nodePort: ""
  persistence: 
    existingClaim: ""
  metrics: 
    enabled: true
  slave:
    persistence: 
      enabled: true
      size: "1Gi"
      storageClass: "my-ceph"
    service: 
      type: "ClusterIP"
      nodePort: ""
  sentinel: 
    enabled: false
    masterSet: "mymaster"
    quorum: "2"
```

**Describe the results you received:**

on related docker nodes, you'll find _redis-cli_ zombie processes:
```
# ps -ef | grep defunc
1001       920 29540  0 04:17 ?        00:00:00 [redis-cli] <defunct>
1001      1519 29540  0 Apr22 ?        00:00:00 [redis-cli] <defunct>
1001      9561 14677  0 Apr15 ?        00:00:00 [redis-cli] <defunct>
1001     12851 29540  0 Apr16 ?        00:00:00 [redis-cli] <defunct>
1001     16168 29540  0 Apr17 ?        00:00:00 [redis-cli] <defunct>
1001     22101 29540  0 Apr18 ?        00:00:00 [redis-cli] <defunct>
1001     24210 14677  0 07:58 ?        00:00:00 [redis-cli] <defunct>
1001     24285 14677  0 Apr22 ?        00:00:00 [redis-cli] <defunct>
1001     27874 14677  0 Apr21 ?        00:00:00 [redis-cli] <defunct>
1001     28288 14677  0 Apr16 ?        00:00:00 [redis-cli] <defunct>
```

also you can see this zombie processes within the running docker container:
```
I have no name!@<pod-name>slave-1:/$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
1001         1     0  0 Apr14 ?        00:28:46 /opt/bitnami/redis/bin/redis-server *:6379
1001      4539     1  0 Apr22 ?        00:00:00 [redis-cli] <defunct>
1001     12162     1  0 02:17 ?        00:00:00 [redis-cli] <defunct>
1001     20491     1  0 Apr16 ?        00:00:00 [redis-cli] <defunct>
1001     25841     1  0 Apr18 ?        00:00:00 [redis-cli] <defunct>
1001     27819     0  0 14:17 pts/0    00:00:00 bash
1001     27837 27819  0 14:17 pts/0    00:00:00 ps -ef
1001     30713     1  0 Apr17 ?        00:00:00 [redis-cli] <defunct>
```

**Describe the results you expected:**
having no zombie processes after some days the docker container is running.

**Version**

- redis-bitnami image version: `docker.io/ranchercharts/bitnami-redis:5.0.5-debian-9-r95`

- OS version:
```
CentOS Linux release 7.7.1908 (Core)
```

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 128
  Running: 98
  Paused: 0
  Stopped: 30
 Images: 82
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.2-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.6GiB
 Name: smb-05
 ID: I6EM:M3JH:VFHB:5QDX:WNKV:MD77:3BTQ:EW6T:5NAB:ZU4B:OK4J:LMKX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
