### ISSUE TITLE
timeout reached before the port went into state "inuse"

### ISSUE THREAD

**Issue by Jenuce** [bitnami/bitnami-docker-redis#171]
VirtualBox, centos 8

This is my docker-compose.yml:
```
version: '3'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    container_name: redis-master
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=my_password
    volumes:
      - '/data/redis/master:/bitnami/redis/data'
    networks:
      - redis   

  redis-slave:
    image: 'bitnami/redis:latest'
    container_name: redis-slave
    restart: always
    ports:
      - '6380:6380'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_PASSWORD=my_password
    volumes:
      - '/data/redis/slave:/bitnami/redis/data'
    networks:
      - redis

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    container_name: redis-sentinel
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_SENTINEL_PASSWORD=my_password
    ports:
      - '26379:26379'
    networks:
      - redis

networks:
  redis:
    driver: "bridge"
```
issue:
```
redis-slave       |  01:20:45.62 INFO  ==> Configuring replication mode...
redis-slave       | timeout reached before the port went into state "inuse"
```

how to resolve it?
