### ISSUE TITLE
Failed run redis in k8s if "redis" DNS name resolved to something else

### ISSUE THREAD

**Issue by Panoptik** [bitnami/bitnami-docker-redis#175]
**Description**
I'm trying to install bitnami/redis:6.0.5 docker image as helm package into kubernetes.
If I named my service exactly "redis" - redis pod (container) is failed at start with next output
```
 16:05:16.63 
 16:05:16.63 Welcome to the Bitnami redis container
 16:05:16.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
 16:05:16.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
 16:05:16.65 
 16:05:16.66 INFO  ==> ** Starting Redis setup **
 16:05:16.72 INFO  ==> Initializing Redis...

 16:05:16.94 INFO  ==> ** Redis setup finished! **
 16:05:16.97 INFO  ==> ** Starting Redis **

*** FATAL CONFIG FILE ERROR (Redis 6.0.5) ***
Reading the configuration file, at line 92
>>> 'port tcp://10.110.113.142:6379'
argument couldn't be parsed into an integer
```
Where ip 10.100.113.142 is the k8s service ip.
`kubectl get service`

```
NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
redis                             NodePort    10.110.113.142   <none>        6379:30679/TCP   21m
```

**Steps to reproduce the issue:**
1. Start minikube kubernetes instance, or use any available kubernetes instance with version 1.17
2. Apply next manifest into kubernetes cluster
with `kubectl apply -f redis.yaml`
```yaml
# redis.yaml
---
# Source: redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-redis-pass
stringData:
  redisPassword: password
---
# Source: redis/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    tier: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    tier: redis
---
# Source: redis/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    tier: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: redis
  template:
    metadata:
      labels:
        app: redis
        tier: redis
    spec:
      containers:
        - image: "bitnami/redis:6.0.5"
          name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-redis-pass
                  key: redisPassword
          ports:
            - containerPort: 6379
              name: redis

```
3. Check redis pod status: **CrashLoopBackOff**, but should be **Running** 
`kubectl get pods | grep redis`
```
redis-76486448b9-tr98w                            0/1     CrashLoopBackOff   9          23m
```

**Describe the results you received:**
If I change service name to something else that redis, for example "redis-service", all works fine.
Somehow redis container during starting make tcp call to "redis" host, which actually point to kubernetes service IP.

**Describe the results you expected:**
I expect that container should start without any unexpected calls to "redis" DNS name.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
6.0.5, but also reproduced with 5.* versions as well
- Output of `docker version`:

```
Client:
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.9
 Git commit:        6a30dfca03
 Built:             Mon Sep 16 03:56:22 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.9
  Git commit:       6a30dfca03
  Built:            Wed Sep 11 22:45:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.3-14-g449e9269
  GitCommit:        449e926990f8539fd00844b26c07e2f1e306c760
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:  
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 210
  Running: 107
  Paused: 0
  Stopped: 103
 Images: 180
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 449e926990f8539fd00844b26c07e2f1e306c760
 runc version: 
 init version: 
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.3.0-59-generic
 Operating System: Ubuntu 19.10 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.18GiB
 Name: minikube
 ID: X4J7:4NUB:ARPI:MQ32:Q4HS:L2JP:M344:ZM2V:Y4EV:KJJ7:ZJU5:MEMT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=docker
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- kubectl version  
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, I am sorry but I don't fully understand how are you deploying Redis. Are you using the [Bitnami Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redis) (`helm install redis bitnami/redis`) or are you creating your own k8s manifest using the bitnami container image (`bitnami/redis:6.0.5`)?

**Comment by Panoptik** [comment]
I've created my own chart using `bitnamiredis:6.0.5`

**Comment by carrodher** [comment]
Ok, thanks I am taking a look at the issue as I was able to reproduce it.

Replacing
```yaml
 kind: Service
 metadata:
   name: redis-svc
```
by
```yaml
 kind: Service
 metadata:
   name: redis
```
(basically removing the `-svc` suffix), the deployment is failing with this error:
```
 15:40:19.06 INFO  ==> ** Starting Redis **
*** FATAL CONFIG FILE ERROR (Redis 6.0.5) ***
Reading the configuration file, at line 92
>>> 'port tcp://10.108.226.199:6379'
argument couldn't be parsed into an integer
```

The source of the issue seems to be in [the libredis.sh file](https://github.com/bitnami/bitnami-docker-redis/blob/master/6.0/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L451):
```bash
        debug "Setting Redis config file..."
        redis_conf_set port "$REDIS_PORT"
```
I added more debug here by creating my own image and I found the following:
- When using `name: redis-svc`, the env. variable `REDIS_PORT` is set to `6379`
- But when using `name: redis`, the env. variable `REDIS_PORT` is set to `tcp://10.108.226.199:6379`, that is not a valid value in the config file and produce the error (`argument couldn't be parsed into an integer`)

This is just an update, I will continue investigating the issue.
