### ISSUE TITLE
Cant open the append only file - Permission Denied - Already owned by (1001)

### ISSUE THREAD

**Issue by anandanand84** [bitnami/bitnami-docker-redis#177]
**Description**

Cant open the append only file - Permission Denied. Even after setting up the correct permissions in directory. Can't seem to resolve the issue.

**Steps to reproduce the issue:**

Basic docker run command with data dir and config dir mapping triggers the error. See below images for all the permissions of the folder and the command executed.

![bitnami redis](https://user-images.githubusercontent.com/5538452/86847241-a036ba00-c071-11ea-8184-da176abc17e5.png)

**Describe the results you received:**

Cant open the append only file - Permission Denied

**Describe the results you expected:**

Redis runs fine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
[node1] (local) root@192.168.0.18 ~
docker --version
Docker version 19.03.11, build 42e35e61f3
```

- Output of `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-184-generic
 Operating System: Alpine Linux v3.12 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.4GiB
 Name: node1
 ID: CN5C:X4HG:FRSE:JC53:IZ4G:TIDJ:CEQ7:GKDB:CW3S:3QQE:Y54U:RTEE
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 23
  Goroutines: 43
  System Time: 2020-07-07T21:16:37.380474569Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.1
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Tried in a ubuntu 20.04 with docker as well as labs.play-with-docker.com same result in both

**Comment by juan131** [comment]
Hi @anandanand84 

This issue has been reported before (e.g. https://github.com/bitnami/bitnami-docker-redis/issues/121). Could you please ensure the group has also writing permissions in the data directory before starting the containers?

```console
$ chmod -R g+rwX ./data
```

Once you do so, try it again. If the problem persists. Please run the command below and share the output:

```console
$ docker run -e ALLOW_EMTPY_PASSWORD=yes \
    -v $(pwd)/conf/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf \
    -v $(pwd)/data:/bitnami/redis/data \
    bitnami/redis:latest -- ls -la /bitnami/redis/data
```

**Comment by anandanand84** [comment]
here is logs after running
```
$ chmod -R g+rwX ./data
```

![Capture](https://user-images.githubusercontent.com/5538452/86982728-97b4b100-c14f-11ea-99e3-84b1e5360a25.PNG)

**Comment by juan131** [comment]
Hi @anandanand84 

Please try using the Docker Compose below:

```yaml
version: '2'

services:
  permission-adapter:
    image: 'docker.io/bitnami/minideb'
    command: chmod -R g+rwX /data
    volumes:
      - './data:/data'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - './data:/bitnami/redis/data'
      - './conf/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    depends_on:
      - permission-adapter
```

Simply run the command: `docker-compose up`. As you can see, I'm using a container to fix the permissions in the volume that will be mounted in Redis beforehand.

**Comment by namlt3820** [comment]
Hi @juan131, I'm using the exact docker-compose file as you suggested, with my redis.conf file as follows:

```
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
```
But I still get the same error

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Starting bitnami-redis-cluster_permission-adapter_1 ... done
Starting bitnami-redis-cluster_redis_1              ... done
Attaching to bitnami-redis-cluster_permission-adapter_1, bitnami-redis-cluster_redis_1
bitnami-redis-cluster_permission-adapter_1 exited with code 0
redis_1               | redis 03:57:55.03
redis_1               | redis 03:57:55.03 Welcome to the Bitnami redis container
redis_1               | redis 03:57:55.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis_1               | redis 03:57:55.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis_1               | redis 03:57:55.03
redis_1               | redis 03:57:55.04 INFO  ==> ** Starting Redis setup **
redis_1               | redis 03:57:55.05 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis_1               | redis 03:57:55.05 INFO  ==> Initializing Redis
redis_1               | redis 03:57:55.06 INFO  ==> ** Redis setup finished! **
redis_1               |
redis_1               | redis 03:57:55.08 INFO  ==> ** Starting Redis **
redis_1               | 1:C 07 Jun 2021 03:57:55.086 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1               | 1:C 07 Jun 2021 03:57:55.086 # Redis version=6.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1               | 1:C 07 Jun 2021 03:57:55.086 # Configuration loaded
redis_1               | 1:M 07 Jun 2021 03:57:55.087 # Can't open the append-only file: Permission denied
```

Do you have any idea what I'm missing here? Thanks

**Comment by juan131** [comment]
Hi @namlt3820 

I guess you're also mounting a local directory (I was using `./data` in my example). Could you run the command below (replace `./data` with any other directory you're using if applies) and share the output? I'd like to take a look to the ownership + permissions configuration of the directory

```console
ls -la ./data
```

**Comment by namlt3820** [comment]
@juan131 Thank you and yes, like you said, I mount a local directory which is `./data` as well. Here is the output from your command `ls -la ./data`

```
total 8
drwxrwxr-x 2 root   root   4096 Jun  7 07:14 .
drwxrwxr-x 4 ubuntu ubuntu 4096 Jun  7 07:14 ..
```

Here is my docker-compose.yml
```
version: '2'

services:
  permission-adapter:
    image: 'docker.io/bitnami/minideb'
    command: chmod -R g+rwX /data
    volumes:
      - './data:/data'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - './data:/bitnami/redis/data'
      - './redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf'
    depends_on:
      - permission-adapter
```

**Comment by namlt3820** [comment]
I know that the user ID running `redis-server` is `1001`, but using this docker-compose file still produce the same error, i.e. empty ./data folder
```
version: '2'

services:
  permission-adapter:
    image: 'docker.io/bitnami/minideb'
    command: bash -c "chmod -R 777 /data && chown -R 1001:1001 /data"
    volumes:
      - './data:/data'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - './data:/bitnami/redis/data'
      - './redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf'
    depends_on:
      - permission-adapter
```

**Comment by namlt3820** [comment]
Hi @juan131 Did you manage to reproduce the bug? if you didn't, please simply ignore my message. Thank you. I found that if I set appendonly to no, then redis server started successfully. But I need that feature to be implemented in production.

**Comment by juan131** [comment]
Hi @namlt3820 

Let's try to figure out why it fails when setting `appendonly yes` in the **redis.conf** file...

First try using the configuration below in your custom `redis.conf`:

```conf
dir /bitnami/redis/data
# Enable AOF https://redis.io/topics/persistence#append-only-file
appendonly yes
# Disable RDB persistence, AOF persistence already enabled
save ""
```

And retry, to see if the problem persists.

---

I noticed that you're setting `cluster-config-file nodes.conf` but I don't see any **nodes.conf** mounted in your Redis container. This could be problematic.

**Comment by namlt3820** [comment]
Wow, after almost a day, thank you kind sir @juan131 ! And please allow me to clarify two things:

1. You’re absolutely correct about the additional code of the redis.conf file. I copied the conf file from a tutorial that’s not involved with docker. So whenever the redis server started successfully, I type CONFIG get dir and received back the root directory `/`.  It made me very suspicious, because I knew it should be /bitnami/redis/data directory. Your very line `dir bitnami/redis/data` confirmed my suspicions. Sorry I didn't read the docs carefully.

2. About the nodes.conf file thing. Yes, I ran to that problem as well. Luckily it was the same as the redis.conf problem, all about owner and permission stuff. So I used your method and made the redis server ran successfully  with this docker-compose.file 

```yaml
version: '2'

services:
  permission-adapter:
    image: 'docker.io/bitnami/minideb'
    command: bash -c "chown -R 1001 /data  /nodes-conf && chmod -R 777 /data /nodes-conf"
    volumes:
      - './data:/data'
      - './nodes-conf:/nodes-conf'
  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - './data:/bitnami/redis/data'
      - './redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf'
      - './nodes-conf:/opt/bitnami/redis/nodes-conf'
    depends_on:
      - permission-adapter
```
Again, thank you very much @juan131
