### ISSUE TITLE
Cannot set password using variable

### ISSUE THREAD

**Issue by max2770** [bitnami/bitnami-docker-redis#179]
**Description**

I can't use a variable to set a password in a docker-compose file.  See example below.

**Steps to reproduce the issue:**

1. Pass a password using a variable:
```
version: "3.7"

networks:
  t2_master:
    external:
      name: t2_master
  default:
    driver: bridge 

secrets:
  redis_password:
    file: $SECRETSDIR/redis_password  

services:    

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: unless-stopped
    networks:
      - t2_master
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=/run/secrets/redis_password
    secrets:
      - redis_password  
    volumes:
      - $DOCKER/redis/data:/bitnami/redis/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

**Describe the results you received:**

The password being set in redis is `/run/secrets/redis_password` instead of the value in the file, ie `MyRedisPassword`

**Describe the results you expected:**

Value in the file `MyRedisPassword` should be set as password, as other services do.

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        dd360c7
 Built:             Mon Jun  8 20:23:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:24:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 57
  Running: 44
  Paused: 0
  Stopped: 0
 Images: 59
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version:
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu Core 16
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 31.18GiB
 Name: virtserver
 ID: W6DW:ZTPS:2XEB:BHB5:3YBR:ZPFT:IMJT:3UJK:6D57:JVNB:IT4O:U44C
 Docker Root Dir: /var/snap/docker/common/var-lib-docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.1
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```
