### ISSUE TITLE
Redis Fatal Error, can't open config file '/etc/redis/redis.conf'

### ISSUE THREAD

**Issue by amin224** [bitnami/bitnami-docker-redis#180]
Good day,

I am having trouble running a Redis StatefulSet Pod in my kubernetes cluster due to this error:

> 1:C 10 Aug 2020 12:37:15.316 # Fatal error, can't open config file '/etc/redis/redis.conf'

After running my configuration file I am getting this error, so I tried to remove the root permission so that my Pod can have access to reach from the config file but to no avail. I tried to resolve my problem by executing `sudo chmod 777 -R redis` and `sudo chown -R $user:$user redis` to all my redis directories such as:

1. /etc/redis/redis.conf
2. /var/lib/redis
3. /var/run/redis
4. /var/log/redis

Please note that from the link provided `https://hub.docker.com/r/bitnami/redis/` I ran my bitnami/redis docker image with this command as stated in the documentation:
`sudo docker run --name bitnamiredis -e ALLOW_EMPTY_PASSWORD=yes -v /etc/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf -v /var/lib/redis:/bitnami/redis/data bitnami/redis:latest`

My Redis StatefulSet YAML file:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: reddis-stateful
  labels:
      app: reddis
spec:
  serviceName: reddis
  replicas: 1
  selector:
       matchLabels:
              app: reddis
              tier: backend
  template:
    metadata:
      labels:
        app: reddis
        tier: backend
    spec:
      hostNetwork: true
      containers:
      - name: redis
        image: bitnami/redis:latest
        #securityContext:
        #allowPrivilegeEscalation: false
        #runAsUser: 0
        #envFrom:
           #- configMapRef:
                #name: redis-cluster-new
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
        volumeMounts:
              - name: "redis-conf"
                mountPath: "/etc/redis"
                #- name: "redis-data"
                #mountPath: "/var/lib/redis"
      volumes:
      - name: "redis-conf"
        persistentVolumeClaim:
                claimName: reddis
```

**Cluster information:**
Kubernetes version: v1.18.6
Cloud being used: bare-metal
Installation method: kubeadm
Host OS: Ubuntu 18.04
CNI and version: calico
CRI and version: Docker 19.03.6

**Comment by carrodher** [comment]
Hi, sorry I didn't fully understand where are you running the image (and having the issue). Are you using it in a k8s manifest, [Bitnami Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redis), or directly with `docker run`?

As this is a [non-root container](https://docs.bitnami.com/tutorials/work-with-non-root-containers/), please note that the mounted files and directories must have the proper permissions for the UID `1001`. In this [blog post](https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html) you can find more information about how to deal with non-root containers in k8s, in the same way, you can take a look at the [Bitnami Redis Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redis) to see how is used this image in a `StatefulSet`.

**Comment by amin224** [comment]
Hello carrodher,

Thank you for informing me about non-root containers I was not aware of that. I tried to run my bitnami/redis image as a root container as specified in [non-root container](https://docs.bitnami.com/tutorials/work-with-non-root-containers/) but I am still getting the same fatal error mentioned above.

> 1:C 10 Aug 2020 12:37:15.316 # Fatal error, can't open config file '/etc/redis/redis.conf'

Here is my docker-compose file which I included the user: root as specified in the documentation

```
services:
  bitnamiredis:
    container_name: bitnamiredis
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    image: bitnami/redis:latest
    user: root
    volumes:
    - /etc/redis/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    - /var/lib/redis:/bitnami/redis/data
version: '3'
```
**Output after docker-compose up:**
```
Status: Downloaded newer image for bitnami/redis:latest
Creating bitnamiredis ... done
Attaching to bitnamiredis
bitnamiredis    | redis 09:05:14.03 
bitnamiredis    | redis 09:05:14.03 Welcome to the Bitnami redis container
bitnamiredis    | redis 09:05:14.04 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
bitnamiredis    | redis 09:05:14.04 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
bitnamiredis    | redis 09:05:14.05 
bitnamiredis    | redis 09:05:14.05 INFO  ==> ** Starting Redis setup **
bitnamiredis    | redis 09:05:14.07 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
bitnamiredis    | redis 09:05:14.14 INFO  ==> Initializing Redis
bitnamiredis    | redis 09:05:14.18 INFO  ==> ** Redis setup finished! **
bitnamiredis    | 
bitnamiredis    | redis 09:05:14.20 INFO  ==> ** Starting Redis **
bitnamiredis    | 1:C 11 Aug 2020 09:05:14.216 # Can't chdir to '/var/lib/redis': No such file or directory
bitnamiredis exited with code 1
```
