### ISSUE TITLE
Replica-announce-port problem ?

### ISSUE THREAD

**Issue by Louis-T** [bitnami/bitnami-docker-redis#183]
**Description**

Hi,
I think there is a problem with the `replica-announce-port`. It is currently set to `$REDIS_MASTER_PORT_NUMBER` and I feel like it should be `$REDIS_PORT_NUMBER` instead.
As I understand it, replica-announce-port should refer to the port of the current redis instance (replica) and not the master instance port ?

I'm sorry if I'm wrong with this assumption, don't bother to read the rest if this is the case.

**Steps to reproduce the issue:**

1. [First Step]

Set up a redis master & replica : 

``` 
version: '3.7'

services:
  redis-primary:
    image: 'bitnami/redis:6.0'
    network_mode: "host"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_password

  redis-secondary:
    image: 'bitnami/redis:6.0'
    network_mode: "host"
    depends_on:
      - redis-primary
    environment:
      - REDIS_PORT_NUMBER=6380
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST="0.0.0.0"
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_PASSWORD=my_password
```
2. [Second Step]

`docker-compose up`

**Describe the results you received:**

We get 

`redis-primary_1    | 1:M 25 Sep 2020 09:21:59.673 * Synchronization with replica xxx.xxx.xx.xxx:6379 succeeded`

**Describe the results you expected:**

I think we should have

`redis-primary_1    | 1:M 25 Sep 2020 09:21:59.673 * Synchronization with replica xxx.xxx.xx.xxx:6380 succeeded`
