### ISSUE TITLE
REDIS_REPLICA_IP value is ignored

### ISSUE THREAD

**Issue by Javier-Lopez-Morante** [bitnami/bitnami-docker-redis#193]
-------------------------------
    BUG REPORT INFORMATION
-------------------------------
**Description**
REDIS_REPLICA_IP value is ignored in bitnami redis docker version tag `bitnami/redis:6.0.9-debian-10-r43`

**Problem Description**
`REDIS_REPLICA_IP` value (and maybe `REDIS_REPLICA_PORT` also) provided in the environment section of `docker-compose.yml` is ignored when using `REDIS_EXTRA_FLAGS` and a custom `/opt/bitnami/redis/etc/redis.conf` file.

**Steps to reproduce the issue:**

1. Configure `docker-compose.yml` as follows

```
version: '3.7'
services:
  redis:
    image: 'docker.io/bitnami/redis:6.0.9'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_REPLICATION_MODE=master
      - REDIS_REPLICA_IP=172.17.17.1
      - REDIS_MASTER_HOST=172.17.17.1
      - REDIS_EXTRA_FLAGS=--databases 1 --always-show-logo yes --loglevel notice --logfile ""
    ports:
      - '172.17.17.1:6379:6379'
    volumes:
      - './redis/data:/bitnami/redis/data'
      - './redis/config:/opt/bitnami/redis/etc/'
```

2. create folders `[project]/redis/config` and `[project]/redis/data` and write a `[project]/redis/config/redis.conf` file with following values:
```
bind 0.0.0.0
protected-mode no
```

3. change permissions from [project] folder to redis folder in order to avoid read/write issues 
```
chmod -R 777 redis
```

4. start redis with following command
```
docker-compose -f docker-compose.yml up -d
```

5. force a config rewrite
```
docker exec -ti [project]_redis_1 redis-cli config rewrite
```

**results received:**
redis-cli shows `OK`

**What actually happens**
some of the values from environment variables in docker-compose are not written to redis.conf file
Current redis.conf
```
bind 0.0.0.0
protected-mode no
databases 1 
always-show-logo yes 
```

Expected redis.conf
```
bind 0.0.0.0
protected-mode no
databases 1 
always-show-logo yes 
replica-announce-ip "172.17.17.1"
replica-announce-port 6379
loglevel notice
logfile ""
```

**Describe the results you expected:**
all the values provided in the environment variables in docker-compose should be written (persisted) to custom redis.conf file

**Additional information:**

**Version**
- Output of `docker version`:
```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-1062.18.1.el7.x86_64
Operating System: OpenShift Enterprise
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 30.68GiB
Name: noname-linux-server
ID: ------
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
