### ISSUE TITLE
[Disk Usage] container eats all disk space

### ISSUE THREAD

**Issue by cowbjt** [bitnami/bitnami-docker-redis#198]
**Description**

Hi there,

Here is my situation:
1. The container is getting bigger and bigger
2. I set max size of appendonly.aof to 64MB
3. Is there any way to check what takes the disk space? and how to fix it?

Thanks for helping.

- `docker system df -v`:

```
Images space usage:
REPOSITORY  TAG. IMAGE ID. CREATED  SIZE. SHARED SIZE  UNIQUE SIZE  CONTAINERS
06a5b673a563  bitnami/redis:latest  "/entrypoint.sh /run…"   0  30.7GB  12 months ago  Up 6 months  redisdocker_redis_1
```

- `redisdocker/redis/data$ ls -lh`:

```
total 65M
-rw-r--r-- 1 joeychen root 182 Oct  7 00:47 admin
-rw-r--r-- 1 joeychen root 182 Oct  7 00:46 apache
-rw-r--r-- 1 joeychen root 65M Oct 17 12:59 appendonly.aof
-rw-r--r-- 1 joeychen root 182 Oct  7 00:46 nginx
-rw-r--r-- 1 joeychen root 182 Oct  7 00:47 nobody
-rw-r--r-- 1 joeychen root 182 Oct  7 00:45 redis
-rw-r--r-- 1 joeychen root 182 Oct  7 00:45 root
-rw-r--r-- 1 joeychen root 209 Oct 17 11:31 systemdd
-rw-r--r-- 1 joeychen root 182 Oct  7 00:46 tomcat
-rw-r--r-- 1 joeychen root 182 Oct  7 00:47 user
-rw-r--r-- 1 joeychen root 182 Oct  7 00:47 web
-rw-r--r-- 1 joeychen root 182 Oct  7 00:47 www
-rw-r--r-- 1 joeychen root 182 Oct  7 00:46 www-data
```

- yml file

```
version: '3'
services:
    redis:
        image: 'bitnami/redis:latest'
        ports:
            - "6379:6379"
        env_file: .env
        restart: always
        volumes:
            - ./redis/data:/bitnami/redis/data
```

- .env file

```
REDIS_PASSWORD=xxxxx
REDIS_MASTER_PORT_NUMBER=6379
```
