### ISSUE TITLE
Error after docker-compose up -d

### ISSUE THREAD

**Issue by michel-el-hajj** [bitnami/bitnami-docker-redis#204]
I needed to delete my volume and start fresh.
I did the following:
```
docker-compose down -v
docker-compose up -d
```
I am getting the following error.

08:53:41.39 Welcome to the Bitnami redis container
 08:53:41.39 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
 08:53:41.39 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
 08:53:41.40
 08:53:41.40 INFO  ==> ** Starting Redis setup **
 08:53:41.42 DEBUG ==> Validating settings in REDIS_* env vars..
 08:53:41.42 INFO  ==> Initializing Redis...
 08:53:41.43 DEBUG ==> Ensuring expected directories/files exist...
 08:53:41.45 DEBUG ==> Setting Redis config file...
sed: -e expression #1, char 38: unknown option to `s'

here is my docker-compose.yml file

```
version: '3'

services:
  redis:
    image: 'bitnami/redis:4.0.14'
    restart: always
    network_mode: "host"
    sysctls:
      - net.core.somaxconn=511
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,SHUTDOWN
      - REDIS_PASSWORD=P@ssw0rd
      - BITNAMI_DEBUG=true

    labels:
      kompose.service.type: nodeport
    volumes:
      - 'redis_data:/bitnami/redis'

volumes:
  redis_data:
    driver: local
```
