### ISSUE TITLE
active ssl with kubernetes secret

### ISSUE THREAD

**Issue by calvinShan** [bitnami/bitnami-docker-redis#207]
Hi,

In your document, we see that we could active ssl by using the env varaibles as REDIS_TLS_CERT_FILE, REDIS_TLS_KEY_FILE, REDIS_TLS_CA_FILE.
However, we have already created a secret which contains the tls

Could we use kubernetes secret to active ssl pls?

my code:
```

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.redis.iot.namespace }}
  name: {{ template "iot-redis-back.fullname" . }}
  labels:
    app: {{ template "iot-redis-back.name" . }}
    chart: {{ template "iot-redis-back.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ template "iot-redis-back.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "iot-redis-back.name" . }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: {{ template "iot-redis-back.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: REDIS_PASSWORD
          value: "{{ .Values.redis.password }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
          protocol: TCP
          name: redis-port
      tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
```

**Comment by Mauraza** [comment]
Hi @calvinShan,

You need to set to 'yes'  the variable `REDIS_TLS_ENABLED`,  mount the volume with the certificates... you can check our [Redis chart](https://github.com/bitnami/charts/tree/master/bitnami/redis) and the necessary parameters https://github.com/bitnami/charts/tree/master/bitnami/redis#securing-traffic-using-tls

**Comment by calvinShan** [comment]
> Hi @calvinShan,
> 
> You need to set to 'yes' the variable `REDIS_TLS_ENABLED`, mount the volume with the certificates... you can check our [Redis chart](https://github.com/bitnami/charts/tree/master/bitnami/redis) and the necessary parameters https://github.com/bitnami/charts/tree/master/bitnami/redis#securing-traffic-using-tls

thanks for your reply, but no way to use kubernetes secret to do this? the kubernetes secret contains the key and certificat

**Comment by migruiz4** [comment]
Hi @calvinShan,

I think I don't understand what you try to say.

You need to create a secret containing the Redis certificates and mount it as a volume in your deployment.

Modifying the previous Deployment you shared, it should look like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.redis.iot.namespace }}
  name: {{ template "iot-redis-back.fullname" . }}
  labels:
    app: {{ template "iot-redis-back.name" . }}
    chart: {{ template "iot-redis-back.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ template "iot-redis-back.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "iot-redis-back.name" . }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: {{ template "iot-redis-back.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.password }}"
            - name: REDIS_TLS_ENABLED
              value: "yes"
            - name: REDIS_TLS_PORT
              value: {{ .Values.redis.containerPort | quote }}
            - name:  REDIS_TLS_CERT_FILE
              value: "/opt/bitnami/redis/certs/tls.crt"
            - name:  REDIS_TLS_KEY_FILE
              value: "/opt/bitnami/redis/certs/tls.key"
            - name:  REDIS_TLS_CA_FILE
              value: "/opt/bitnami/redis/certs/ca.crt"
            - name:  REDIS_TLS_AUTH_CLIENTS
              value: "yes"
          volumeMounts:
            - name: redis-certificates
              mountPath: /opt/bitnami/redis/certs
              readOnly: true
          resources:
  {{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.redis.containerPort }}
              protocol: TCP
              name: redis-port
      tolerations:
{{ toYaml .Values.tolerations | indent 12 }}
      volumes:
        - name: redis-certificates
          secret:
            secretName: "<your_redis_secret>"
```

If you are trying to create your own template, I would recommend having a look at our Charts repository (https://github.com/bitnami/charts).

There you can find many examples, including a Helm chart for Redis.
