### ISSUE TITLE
mv: cannot move '/opt/bitnami/redis/etc/redis-default.conf' to a subdirectory of itself, '/opt/bitnami/redis/etc/redis.conf'

### ISSUE THREAD

**Issue by huyouba1** [bitnami/bitnami-docker-redis#208]
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Redis setup **
INFO  ==> Initializing Redis...
mv: cannot move '/opt/bitnami/redis/etc/redis-default.conf' to a subdirectory of itself, '/opt/bitnami/redis/etc/redis.conf'

**Comment by javsalgar** [comment]
Hi,

Could you provide the docker-compose file you are using? This error seems familiar to me. I think it has to do with mounting local volumes and you are mounting a file that does not exist, therefore it creates a folder.

**Comment by huyouba1** [comment]
Hello, I deployed redis with kubernetes. This is my yaml file。I suspect that there is something wrong with my machine. I have been dispatched to other machines, which are now normal

```

COMPUTED VALUES:
cluster:
  enabled: true
  slaveCount: 2
configmap: ""
global:
image:
  repository: bitnami/redis
  tag: 4.0.11
master:
  affinity: {}
  args: []
  disableCommands: FLUSHDB,FLUSHALL
  extraFlags: []
  livenessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    path: /bitnami/redis/data
    size: 10Gi
    storageClass: local-path
    subPath: ""
  podAnnotations: {}
  podLabels: {}
  port: 6379
  readinessProbe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  service:
    annotations: {}
    loadBalancerIP: null
    port: 6379
    type: ClusterIP
  statefulset:
    updateStrategy: RollingUpdate

---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-redis-master
  labels:
    app: redis
    chart: redis-4.2.10
    release: "redis"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "redis"
    role: master
---
# Source: redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-redis-master
  labels:
    app: redis
    chart: redis-4.2.10
    release: "redis"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      release: "redis"
      role: master
      app: redis
  serviceName: redis-redis-master
  template:
    metadata:
      labels:
        release: "redis"
        chart: redis-4.2.10
        role: master
        app: redis
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: "default"
      containers:
      - name: redis-redis
        image: "bitnami/redis:4.0.11"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-redis
              key: redis-password
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DISABLE_COMMANDS
          value: FLUSHDB,FLUSHALL
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: health
          mountPath: /health
        - name: redis-data
          mountPath: /bitnami/redis/data
          subPath:
      initContainers:
      - name: volume-permissions
        image: "bitnami/minideb:latest"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/chown", "-R", "1001:1001", "/bitnami/redis/data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
          subPath:
      volumes:
      - name: health
        configMap:
          name: redis-redis-health
          defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app: "redis"
          component: "master"
          release: "redis"
          heritage: "Helm"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
        storageClassName: "local-path"
  updateStrategy:
    type: RollingUpdate
```

**Comment by huyouba1** [comment]
Hi,

This is my runtime manifest。
```
---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-redis-master
  labels:
    app: redis
    release: "redis"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "redis"
    role: master
---
# Source: redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-redis-master
  labels:
    app: redis
    release: "redis"
spec:
  selector:
    matchLabels:
      release: "redis"
      role: master
      app: redis
  serviceName: redis-redis-master
  template:
    metadata:
      labels:
        release: "redis"
        role: master
        app: redis
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: "default"
      containers:
      - name: redis-redis
        image: "bitnami/redis:4.0.11"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-redis
              key: redis-password
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DISABLE_COMMANDS
          value: FLUSHDB,FLUSHALL
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - sh
            - -c
            - /health/ping_local.sh
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: health
          mountPath: /health
        - name: redis-data
          mountPath: /bitnami/redis/data
          subPath:
      initContainers:
      - name: volume-permissions
        image: "bitnami/minideb:latest"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/chown", "-R", "1001:1001", "/bitnami/redis/data"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
          subPath:
      volumes:
      - name: health
        configMap:
          name: redis-redis-health
          defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app: "redis"
          component: "master"
          release: "redis"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
        storageClassName: "local-path"
  updateStrategy:
    type: RollingUpdate
```
