### ISSUE TITLE
docker-compose file with url context fails to build

### ISSUE THREAD

**Issue by seekingThat** [bitnami/bitnami-docker-redis#210]
Could you please clarify if there is anything wrong with the below docker-compose.yml file ? docker-compose up fails for this yaml file

`[test]$ cat docker-compose.yml`
```yaml
version: '3.7'
networks:
  redisnet:
    ipam:
      config:
        - subnet: 12.0.1.0/24
services:
  redis:
    image: bitnami/redis:latest
    build:
      context: 'https://github.com/bitnami/bitnami-docker-redis.git#master:6.2/debian-10'
    networks:
      redisnet:
        ipv4_address: 12.0.1.2
    volumes:
      - /opt:/opt
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    privileged: true
    tty: true
```

**Description**

Could you please clarify if there is anything wrong with the below docker-compose.yml file ? docker-compose up fails for this yaml file
Please let me know if you need any further information

`[test]$ cat docker-compose.yml`
```yaml
version: '3.7'
networks:
  redisnet:
    ipam:
      config:
        - subnet: 12.0.1.0/24
services:
  redis:
    image: bitnami/redis:latest
    build:
      context: 'https://github.com/bitnami/bitnami-docker-redis.git#master:6.2/debian-10'
    networks:
      redisnet:
        ipv4_address: 12.0.1.2
    volumes:
      - /opt:/opt
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    privileged: true
    tty: true
```
**Steps to reproduce the issue:**

1. Copy the above docker-compose.yml into a separate directory
2. Run the command "docker-compose up -d"  And this results in an error message shown below

**Describe the results you received:**

```bash
[test]$ docker-compose up -d
Removing test_redis_1
Recreating 33b3138d0f3c_test_redis_1 ... error


ERROR: for 33b3138d0f3c_test_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/opt/bitnami/scripts/redis/entrypoint.sh": stat /opt/bitnami/scripts/redis/entrypoint.sh: no such file or directory: unknown

ERROR: for redis  Cannot start service redis: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/opt/bitnami/scripts/redis/entrypoint.sh": stat /opt/bitnami/scripts/redis/entrypoint.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

**Describe the results you expected:**
The build should go through smoothly and redis-server is to be instantiated.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
[test]$ docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:32:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


```

- Output of `docker info`:

```
[test]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 9
  Running: 7
  Paused: 0
  Stopped: 2
 Images: 31
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.13.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.51GiB
 Name: skdevp2.pdsea.f5net.com
 ID: ETFN:KLJD:K7V2:PEVS:UC4D:4MIH:YULU:7JFZ:OYGL:ZZBA:PTE4:CPYI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
[test]$ docker-compose --version
docker-compose version 1.25.0, build 0a186604

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment]
Hi @seekingThat,

The error is related to the volume. 
```yaml
version: '3.7'
networks:
  redisnet:
    ipam:
      config:
        - subnet: 12.0.1.0/24
services:
  redis:
    image: bitnami/redis:latest
    build:
      context: 'https://github.com/bitnami/bitnami-docker-redis.git#master:6.2/debian-10'
    networks:
      redisnet:
        ipv4_address: 12.0.1.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    privileged: true
    tty: true

volumes:
  redis_data:
    driver: local
```
The volume can be changed but the directory needs to be `/bitnami` 
You can check this part of the README.md https://github.com/bitnami/bitnami-docker-redis/#persisting-your-database
