### ISSUE TITLE
Dir value in configure change after startup

### ISSUE THREAD

**Issue by hungnvk54** [bitnami/bitnami-docker-redis#216]
**Description**
- I use the redis as cluster and sentinel. 1 master, 2 slave. deploy in swarm mode
- Here is my docker compose file

```
redis-master:
        image: 'bitnami/redis:latest'
        #volumes:
        #  - sentinel-conf:/etc/redis
        deploy:
          endpoint_mode: vip
          mode: global
          placement:
            constraints:
              - node.labels.ntype == master
        environment:
          - REDIS_REPLICATION_MODE=master
          - ALLOW_EMPTY_PASSWORD=yes
          #- REDIS_REPLICA_IP=ec2-13-213-173-103.ap-southeast-1.compute.amazonaws.com
          #- REDIS_ANNOUNCE_PORT=6379
          #- REDIS_PASSWORD=str0ng_passw0rd
        ports:
          - 6379:6379
        networks:
            - cluster
    redis-slave:
        image: 'bitnami/redis:latest'
        #volumes:
          #- redis-data:/data
          #- redis-conf:/etc/redis
        deploy:
          endpoint_mode: vip
          mode: global
          placement:
            constraints:
              - node.labels.ntype == slave1
        environment:
          - REDIS_REPLICATION_MODE=slave
          - REDIS_MASTER_HOST=redis-master
          - ALLOW_EMPTY_PASSWORD=yes
          #- REDIS_REPLICA_IP=ec2-54-255-175-131.ap-southeast-1.compute.amazonaws.com
          #- REDIS_ANNOUNCE_PORT=6380
          #- REDIS_MASTER_PASSWORD=str0ng_passw0rd
          #- REDIS_PASSWORD=str0ng_passw0rd
        ports:
          - 6380:6379
        networks:
            - cluster
        
    redis_slave_node2:
        image: 'bitnami/redis:latest'
        #volumes:
          #- redis-data:/data
          #- redis-conf:/etc/redis
        environment:
          - REDIS_REPLICATION_MODE=slave
          - REDIS_MASTER_HOST=redis-master
          - ALLOW_EMPTY_PASSWORD=yes
          #- REDIS_REPLICA_IP=ec2-13-212-52-126.ap-southeast-1.compute.amazonaws.com
          #- REDIS_ANNOUNCE_PORT=6381
          #- REDIS_MASTER_PASSWORD=str0ng_passw0rd
          #- REDIS_PASSWORD=str0ng_passw0rd
        deploy:
          mode: global
          placement:
            constraints:
              - node.labels.ntype == slave2
        ports:
          - 6381:6379    
        networks:
            - cluster

    redis-sentinel:
        image: 'bitnami/redis-sentinel:latest'
        #volumes:
          #- redis-data:/data
          #- redis-conf:/etc/redis
        environment:
          - REDIS_MASTER_HOST=redis-master
        deploy:
          mode: global
          placement:
            constraints:
              - node.labels.sentinel == true
        ports:
          - "26379:26379"
        #environment:
        #  - REDIS_MASTER_PASSWORD=str0ng_passw0rd
        networks:
            - cluster
```

After all start, and redis master node startup, I run following command:

`
>config get dir
> (output): "/bitnami/redis/data". it is same as in default configure file
`

After 15 minutes running, I check the log, the error was print as follow:

`
Failed opening the RDB file crontab (in server root dir /etc) for saving: Permission denied
`
Then, I recheck the config by running following command:
>config get dir
> (output): "/etc": This will make the error
`

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS
