### ISSUE TITLE
Redis MISCONF and permission denied with docker-compose

### ISSUE THREAD

**Issue by amirjani** [bitnami/bitnami-docker-redis#220]
Hi, my docker-compose.yaml looks like below: 

```yaml
version: "3.3"
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/bitnami/redis/data
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    networks:
      - network
```

when I'm run it on server, I'm facing ```Failed opening the RDB file dump.rdb (in server root dir /bitnami/redis/data) for saving: Permission denied```

is there any help?
