### ISSUE TITLE
Replication with ACL does not work anymore

### ISSUE THREAD

**Issue by firstdorsal** [bitnami/bitnami-docker-redis#228]
Hi!
I want to replicate my main redis db on a second machine using the replication feature.
I want to use ACL to restrict their access to certain commands.

This worked before as far as i remember... but i dont know what the issue is now.
Thank you.

This gets logged over and over and over again by the replicant/subordinate
```
1:S 25 Jan 2022 18:06:10.716 * (Non critical) Master does not understand REPLCONF capa: -NOAUTH Authentication required.
1:S 25 Jan 2022 18:06:10.716 * Partial resynchronization not possible (no cached master)
1:S 25 Jan 2022 18:06:10.717 # Unexpected reply to PSYNC from master: -NOAUTH Authentication required.
1:S 25 Jan 2022 18:06:10.717 * Retrying with SYNC...
1:S 25 Jan 2022 18:06:10.717 # MASTER aborted replication with an error: NOAUTH Authentication required.
1:S 25 Jan 2022 18:06:10.717 * Reconnecting to MASTER pektin-redis-direktor:6379 after failure
1:S 25 Jan 2022 18:06:10.718 * MASTER <-> REPLICA sync started
1:S 25 Jan 2022 18:06:10.719 * Non blocking connect for SYNC fired the event.
1:S 25 Jan 2022 18:06:10.720 * Master replied to PING, replication can continue...
1:S 25 Jan 2022 18:06:10.720 * (Non critical) Master does not understand REPLCONF listening-port: -NOAUTH Authentication required.
```

the acl of the main server:
```
user default off
user r-pektin-server on resetchannels allkeys -@all +GET +MGET +KEYS #5656c5ce2aad411f7d230cbed9913ee5c11481c5aa4aded30ccb3be72cbe6020
user r-pektin-api on resetchannels allkeys -@all +SET +GET +MSET +MGET +DEL +KEYS #d0b2868587d430f620e74095253c72cad86c4fb2c1dfde74d38715f750299f43
user r-pektin-gewerkschaft on +PSYNC +REPLCONF +PING #25c0def0b7353873caaa10b063f8b12c47bacdf10a2d81464751ae5917d12be6
```
the redis.conf of the main server:
```
aclfile /opt/bitnami/redis/mounted-etc/users.acl
slave-read-only yes
protected-mode no
```

the acl of the replicant/subordinate
```
user default off
user r-pektin-server on resetchannels allkeys -@all +GET +MGET +KEYS #bc9f86636d8b9e09d3648e230d91fc56ebd488c851b303d43d0dfcd8a9f97a52
```
the redis.conf of the replicant/subordinate:
```
aclfile /opt/bitnami/redis/mounted-etc/users.acl
replicaof pektin-redis-direktor 6379
masteruser r-pektin-gewerkschaft
protected-mode no
```
the docker-compose  of the replicant/subordinated:
```yml
version: "3.7"
services:
    redis:
        image: bitnami/redis
        user: root
        container_name: pektin-redis-arbeiter
        restart: always
        volumes:
            - db:/bitnami/redis/data
            - ../../config/redis/arbeiter/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf:ro
            - ../../secrets/redis/users.acl:/opt/bitnami/redis/mounted-etc/users.acl:ro
        networks:
            - db
            - pektin-gewerkschaft
        command: "redis-server /opt/bitnami/redis/mounted-etc/redis.conf"
        environment:
            - REDIS_MASTER_PASSWORD=${R_PEKTIN_GEWERKSCHAFT_PASSWORD}
            - REDIS_MASTER_HOST=pektin-redis-direktor
            - REDIS_REPLICATION_MODE=slave
```

the docker-compose of the main server:
```yml
redis:
        image: bitnami/redis
        user: root
        container_name: pektin-redis-direktor
        restart: always
        environment:
            - REDIS_REPLICATION_MODE=master
        volumes:
            - db:/bitnami/redis/data
            - ../config/redis/direktor/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf:ro
            - ../secrets/redis/users.acl:/opt/bitnami/redis/mounted-etc/users.acl:ro
        networks:
            - pektin-gewerkschaft
            - db
        command: "redis-server /opt/bitnami/redis/mounted-etc/redis.conf"
```

both of them have a connection through an overlay network in docker swarm
both of them run redis 6.2.6
i tried using 6.2 and 6.0
using 6.0 it threw me and error that the acl config was incorrect.
