### ISSUE TITLE
Overwrite configuration file in docker compose gives 'permission denied'

### ISSUE THREAD

**Issue by jimi-pz** [bitnami/bitnami-docker-redis#231]
### Name and Version

bitnami/redis:latest

### What steps will reproduce the bug?

I'm using redis latest image inside the docker compose file.
Config is as follows => 

```
version: '3.8'

services:
  redis:
    image: docker.io/bitnami/redis:latest
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,INFO
      - ./containers/redis/config/redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
```
For ur information, running with 'REDIS_AOF_ENABLED=no' did not work.

### What is the expected behavior?

Based on the documentation, an existing configuration should be overwritten with the one defined in the docker-compose file.

### What do you see instead?

![image](https://user-images.githubusercontent.com/1504259/152988308-79ca24f9-724b-4f03-90cb-2892b4bef0af.png)
