### ISSUE TITLE
Can't open the append-only file: Permission denied

### ISSUE THREAD

**Issue by TomlDev** [bitnami/bitnami-docker-redis#236]
### Name and Version

bitnami/redis:6.2

### What steps will reproduce the bug?

Hello,

I am deploying bitnami/redis on my server with ansible and docker-compose. This is my `docker-compose.yml`:

```
lorawan_ttn_redis:
    container_name: lorawan_ttn_redis
    image: bitnami/redis:6.2
    # command: redis-server --appendonly yes
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD={{ redis_password }}
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - "{{ redis_port }}:6379"
```

With ansible I create the directory for redis as followed:

```
- name: Create redis directory
  file:
    path: /srv/lorawan_ttn/data/redis
    state: directory
    owner: 1001
```

And this directory is used as working dir. Redis creates a append only file:

```
$ ll -n
total 8K
-rw-r--r-- 1 1001 0 6.0K Mar 29 10:58 appendonly.aof
```

But if I uncomment the line  `command: redis-server --appendonly yes` and re-deploy, then it creates a dump.rdb:

```
ll -n
total 12K
-rw-r--r-- 1 1001 0 6.0K Mar 29 10:58 appendonly.aof
-rw-r--r-- 1 1001 0  295 Mar 29 11:15 dump.rdb
```

And the logs say `Can't open the append-only file: Permission denied`

### What is the expected behavior?

It should be able to write to the append only file in this directory.

### What do you see instead?

```
$ docker logs lorawan_ttn_redis
redis 07:22:03.34 
redis 07:22:03.34 Welcome to the Bitnami redis container
redis 07:22:03.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis 07:22:03.36 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis 07:22:03.36 

1:C 29 Mar 2022 07:22:03.373 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Mar 2022 07:22:03.373 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Mar 2022 07:22:03.373 # Configuration loaded
1:M 29 Mar 2022 07:22:03.375 * monotonic clock: POSIX clock_gettime
1:M 29 Mar 2022 07:22:03.376 # Can't open the append-only file: Permission denied
redis 07:22:05.05 
redis 07:22:05.06 Welcome to the Bitnami redis container
redis 07:22:05.06 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis 07:22:05.06 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis 07:22:05.06 

1:C 29 Mar 2022 07:22:05.073 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Mar 2022 07:22:05.073 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Mar 2022 07:22:05.073 # Configuration loaded
1:M 29 Mar 2022 07:22:05.074 * monotonic clock: POSIX clock_gettime
1:M 29 Mar 2022 07:22:05.075 # Can't open the append-only file: Permission denied

...
```

### Additional information

`docker-compose version 1.28.6, build unknown`
