### ISSUE TITLE
Permission Denied - /opt/bitnami/redis/tmp

### ISSUE THREAD

**Issue by Anuj28282828** [bitnami/bitnami-docker-redis#240]
### Name and Version

bitnami/bitnami-docker-redis

### What steps will reproduce the bug?

I am getting
mkdir: cannot create directory '/opt/bitnami/redis/tmp' : Permission Denied

I have a limitation that i can't give permissions to root though
Can we somehow override this location?

### What do you see instead?

Permission denied

**Comment by mamachanko** [comment]
We are seeing the same.

As per [Kubernetes Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) We've got the following `Pod` security context:
```yaml
securityContext:                                                                                                                                                                                                               
 runAsGroup: 1000                                                                                                                                                                                                             
 runAsNonRoot: true                                                                                                                                                                                                           
 runAsUser: 1000                                                                                                                                                                                                              
 seccompProfile:                                                                                                                                                                                                              
   type: RuntimeDefault 
```

And this container security context:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - All
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault
```
