### ISSUE TITLE
Redis master/slave replication error : "I/O error reading bulk count from MASTER: Operation now in progress"

### ISSUE THREAD

**Issue by franck-grenier** [bitnami/bitnami-docker-redis#243]
### Name and Version

bitnami/redis:latest

### What steps will reproduce the bug?

Hello Bitnami,
I'm trying to setup a simple master/slave replicated Redis in a docker-compose environment but the replication does not work.

I have 2 nodes : 
- node1 is hosting the master Redis
- node2 has the slave Redis

My master container : 

```
# master
  redis:
    image: bitnami/redis:latest
    container_name: redis-master
    restart: unless-stopped
    ports:
      - 172.10.0.1:6379:6379
    volumes:
      - ${PWD}/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
      - ${PWD}/redis/data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    networks:
      - mynetwork
```

My slave container : 

```
# slave
  redis:
    image: bitnami/redis:latest
    container_name: redis-slave
    restart: unless-stopped
    ports:
      - 172.10.0.2:6379:6379
    volumes:
      - ${PWD}/redis/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
      - ${PWD}/redis/data:/bitnami/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MASTER_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=172.10.0.1
      - REDIS_REPLICA_IP=172.10.0.2
    networks:
      - mynetwork
```

Very simple config, same on each node : 

```
protected-mode no # did not fix my issue...
maxmemory 256mb
maxmemory-policy allkeys-lru
```

As you can see,
I work on a private network on which I confirm communication works. I can telnet on Redis from one node to the other, display `INFO` and `KEYS`.

The `INFO` about replication : 

MASTER
```
# Replication
role:master
connected_slaves:1
slave0:ip=172.10.0.2,port=6379,state=wait_bgsave,offset=0,lag=0
master_failover_state:no-failover
master_replid:2d62483aa609a7574c7cb73d7c7e3491fa8c883f
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1498
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:1498
```

SLAVE
```
# Replication
role:slave
master_host:172.10.0.1
master_port:6379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:1
slave_read_repl_offset:1
slave_repl_offset:1
master_sync_total_bytes:-1
master_sync_read_bytes:0
master_sync_left_bytes:-1
master_sync_perc:-0.00
master_sync_last_io_seconds_ago:1
master_link_down_since_seconds:-1
slave_priority:100
slave_read_only:1
replica_announced:1
connected_slaves:0
master_failover_state:no-failover
master_replid:539864ba6ff947c28f7e96050a1f4ed8304fa162
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0
```

### What is the expected behavior?

Slave Redis should sync with master Redis.

### What do you see instead?

No replication, slave Redis remains empty.

And I get errors from logs.

MASTER
```
1:M 11 May 2022 13:46:12.107 * Replica 172.10.0.2:6379 asks for synchronization
1:M 11 May 2022 13:46:12.107 * Full resync requested by replica 172.10.0.2:6379
1:M 11 May 2022 13:46:12.107 * Starting BGSAVE for SYNC with target: disk
1:M 11 May 2022 13:46:12.107 * Background saving started by pid 349
349:C 11 May 2022 13:46:12.119 * DB saved on disk
349:C 11 May 2022 13:46:12.120 * RDB: 0 MB of memory used by copy-on-write
1:M 11 May 2022 13:46:12.200 * Background saving terminated with success
1:M 11 May 2022 13:46:12.200 # SYNC failed. Can't open/stat DB after BGSAVE: Permission denied
1:M 11 May 2022 13:46:12.200 # Connection with replica 172.10.0.2:6379 lost.
```

SLAVE
```
1:S 11 May 2022 13:46:20.305 * MASTER <-> REPLICA sync started
1:S 11 May 2022 13:46:20.306 * Non blocking connect for SYNC fired the event.
1:S 11 May 2022 13:46:20.308 * Master replied to PING, replication can continue...
1:S 11 May 2022 13:46:20.310 * Partial resynchronization not possible (no cached master)
1:S 11 May 2022 13:46:20.313 * Full resync from master: 2d62483aa609a7574c7cb73d7c7e3491fa8c883f:56
1:S 11 May 2022 13:46:20.406 # I/O error reading bulk count from MASTER: Operation now in progress
1:S 11 May 2022 13:46:20.407 * Reconnecting to MASTER 172.10.0.1:6379 after failure
```

### Additional information

What I already checked : 

- PASSWORD is set correctly through `REDIS_PASSWORD` and `REDIS_MASTER_PASSWORD` Docker env vars. Both have the same value.
- Both master and slave containers have write permission on the data mount. I see files written in there.

Hope you can help !

Thanks
