### ISSUE TITLE
Protected mode is on by default in the latest version

### ISSUE THREAD

**Issue by saikris12** [bitnami/bitnami-docker-redis#245]
### Name and Version

bitnami/redis:latest

### What steps will reproduce the bug?

docker-compose 

```
local-redis:
    image: "bitnami/redis:latest"
    hostname: "local-redis"
    container_name: "local-redis"
    ports:
      - "6479:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
```

### What is the expected behavior?

We should be able to connect to the redis instance from outside the container

### What do you see instead?

DENIED Redis is running in protected mode because protected mode is enabled and no password is set for the default user. In this mode connections are only accepted from the loopback interface. 

### Additional information

We have always been using the latest image of bitnami redis but this issue started popping up this morning.
