### ISSUE TITLE
Redis authentication

### ISSUE THREAD

**Issue by lyhoanglong** [bitnami/bitnami-docker-redis#29]
I set env REDIS_PASSWORD=something. I ran docker-compose up -d, after that I exec to redis container by command:
```
docker exec -it redis bash
```

type command:
```
env | grep REDIS

REDIS_HOST=redis
REDIS_PASSWORD=something
REDIS_PORT=6379
```

when I try redis-cli>ping error show up: NOAUTH Authentication required.

I try to viewed redis config in folder /bitnami/redis/conf/
```
...
requirepass null
...
```

Sorry my bad english. Any idea for this bug? Thanks!

**Comment by prydonius** [comment]
Hi @lyhoanglong,

Are you able to provide your docker-compose file or tell us how we can reproduce the issue?

Thanks!

**Comment by sameersbn** [comment]
@lyhoanglong Since you have enabled the authentication module, you need to provide the authentication password in `redis-cli`. Please try `$ redis-cli -a something`/

**Comment by lyhoanglong** [comment]
@sameersbn It's doesn't work, I try it before. 
@prydonius here my docker-compose.yml

```
redis:
  image: bitnami/redis
  volumes:
    - /var/lib/redis:/bitnami/redis/data
  container_name: redis
  env_file: ./src/.env
```

.env file
```
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=something
```
