### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by StephanX** [bitnami/bitnami-docker-redis#87]
Hi guys,

When used in vanilla kubernetes (1.7) it appears the pod is dropping privileges to user 1001 without first initializing the filesystem.  I'll hack out an init container for my own needs, happy to post it here if you'd find it useful.

```
ku logs -f redis-782614939-vb76t

Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...



Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis/conf'
```

**Comment by 34code** [comment]
noticed the same issue.. rolling back to the old version of redis -- really wanted to try the new LFU caching algo!

**Comment by sameersbn** [comment]
@34code A minor change was required in the kubernetes.yml spec. This issue has been resolved in the latest revision. Please give it a try and let us know. Thank you @StephanX for looking into this issue and suggesting a clean fix.

Closing the issue. Please re-open if you continue to face this issue.

**Comment by 34code** [comment]
tried to do a helm based install using the docker image 

`bitnami/redis:4.0-master`

but getting this message again in logs:

```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis/conf'
```

**Comment by sameersbn** [comment]
Hi @34code, the fix for the `stable/redis` chart has not yet been merged (https://github.com/kubernetes/charts/pull/2380). It should be merged soon. For now, can you apply the changes locally and retry?

```bash
git clone https://github.com/kubernetes/charts
cd charts
git checkout -b sameersbn-redis-0.11.0 master
git pull https://github.com/sameersbn/kubernetes-charts.git redis-0.11.0
helm install --name redis stable/redis/
```

If it resolves the issue you are facing then please upvote on the pull request so that it is merged quickly :slightly_smiling_face:

**Comment by 34code** [comment]
@sameersbn thanks for the PR! However, the logs now show a slightly different error:

```Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing redis
redis   INFO  ==> Validating inputs...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redis'```

**Comment by sameersbn** [comment]
@34code Could you share some details of your setup? And did you use these instructions  https://github.com/bitnami/bitnami-docker-redis/issues/87#issuecomment-334381101 to deploy the helm chart?

I have tested the chart on GKE and Helm with success. It would be great if you could share more details, especially w.r.t the kubernetes setup.

**Comment by 34code** [comment]
@sameersbn sure.. I set up using your comment described here:

```
git clone https://github.com/kubernetes/charts
cd charts
git checkout -b sameersbn-redis-0.11.0 master
git pull https://github.com/sameersbn/kubernetes-charts.git redis-0.11.0
helm install --name redis stable/redis/
```

My kubernetes version on GKE is `1.7.6-gke.1` on master and `1.7.3` on other nodes

**Comment by monotykamary** [comment]
I don't use the helm chart, but I can confirm that using the init container solves the problem. I'm testing a redis-master StatefulSet with redis-slave Deployments on OpenShift Origin v3.6 and it works perfectly:

```
oc adm policy add-scc-to-user anyuid -z default
oc adm policy add-scc-to-user hostmount-anyuid -z default
```

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  serviceName: "redis-master"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      initContainers:
      - name: "fix-non-root-permissions"
        image: "busybox"
        imagePullPolicy: "Always"
        command: [ "chmod", "-R", "g+rwX", "/bitnami" ]
        volumeMounts:
        - name: datadir
          mountPath: /bitnami
      containers:
      - name: master
        image: bitnami/redis:4.0.2-r0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_REPLICATION_MODE
          valueFrom:
            secretKeyRef:
              name: redis-master-secrets
              key: REDIS_REPLICATION_MODE
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-master-secrets
              key: REDIS_PASSWORD
        ports:
        - containerPort: 6379
          name: master
        volumeMounts:
        - name: datadir
          mountPath: /bitnami
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
